/* automatically generated from display-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (display_dialog_ui)
#endif
#ifdef __GNUC__
static const char display_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char display_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"2.24\"/><object class=\"XfceTitledDialog\" id=\"display-"
  "dialog\"><property name=\"can_focus\">False</property><property name=\""
  "title\" translatable=\"yes\">Display</property><property name=\"window_"
  "position\">center-on-parent</property><property name=\"default_width\">"
  "400</property><property name=\"default_height\">350</property><property"
  " name=\"icon_name\">video-display</property><property name=\"type_hint\""
  ">dialog</property><property name=\"subtitle\" translatable=\"yes\">Conf"
  "igure screen settings and layout</property><child internal-child=\"vbox"
  "\"><object class=\"GtkVBox\" id=\"dialog-vbox1\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"spacing\">2</property><child><object class=\"GtkHBox\" id=\""
  "plug-child\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"border_width\">12</propert"
  "y><property name=\"spacing\">12</property><child><object class=\"GtkScr"
  "olledWindow\" id=\"scrolledwindow1\"><property name=\"width_request\">2"
  "00</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"hscrollbar_policy\">automat"
  "ic</property><property name=\"vscrollbar_policy\">automatic</property><"
  "property name=\"shadow_type\">etched-in</property><child><object class="
  "\"GtkTreeView\" id=\"randr-outputs\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">True</property><property name=\"he"
  "aders_visible\">False</property><property name=\"enable_search\">False<"
  "/property><property name=\"show_expanders\">False</property></object></"
  "child></object><packing><property name=\"expand\">True</property><prope"
  "rty name=\"fill\">True</property><property name=\"position\">0</propert"
  "y></packing></child><child><object class=\"GtkTable\" id=\"table1\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"n_rows\">7</property><property name=\"n_c"
  "olumns\">2</property><property name=\"column_spacing\">12</property><pr"
  "operty name=\"row_spacing\">6</property><child><object class=\"GtkCombo"
  "Box\" id=\"randr-reflection\"><property name=\"can_focus\">False</prope"
  "rty></object><packing><property name=\"left_attach\">1</property><prope"
  "rty name=\"right_attach\">2</property><property name=\"top_attach\">6</"
  "property><property name=\"bottom_attach\">7</property><property name=\""
  "y_options\">GTK_FILL</property></packing></child><child><object class=\""
  "GtkComboBox\" id=\"randr-rotation\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property></object><packing><"
  "property name=\"left_attach\">1</property><property name=\"right_attach"
  "\">2</property><property name=\"top_attach\">5</property><property name"
  "=\"bottom_attach\">6</property><property name=\"y_options\">GTK_FILL</p"
  "roperty></packing></child><child><object class=\"GtkComboBox\" id=\"ran"
  "dr-refresh-rate\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property></object><packing><property name=\"le"
  "ft_attach\">1</property><property name=\"right_attach\">2</property><pr"
  "operty name=\"top_attach\">4</property><property name=\"bottom_attach\""
  ">5</property><property name=\"y_options\">GTK_FILL</property></packing>"
  "</child><child><object class=\"GtkComboBox\" id=\"randr-resolution\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property></object><packing><property name=\"left_attach\">1</prope"
  "rty><property name=\"right_attach\">2</property><property name=\"top_at"
  "tach\">3</property><property name=\"bottom_attach\">4</property><proper"
  "ty name=\"y_options\">GTK_FILL</property></packing></child><child><obje"
  "ct class=\"GtkLabel\" id=\"label-reflection\"><property name=\"can_focu"
  "s\">False</property><property name=\"xalign\">0</property><property nam"
  "e=\"label\" translatable=\"yes\">Ref_lection:</property><property name="
  "\"use_underline\">True</property></object><packing><property name=\"top"
  "_attach\">6</property><property name=\"bottom_attach\">7</property><pro"
  "perty name=\"x_options\">GTK_FILL</property><property name=\"y_options\""
  ">GTK_FILL</property></packing></child><child><object class=\"GtkLabel\""
  " id=\"label5\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"xalign\">0</property><p"
  "roperty name=\"label\" translatable=\"yes\">Ro_tation:</property><prope"
  "rty name=\"use_underline\">True</property></object><packing><property n"
  "ame=\"top_attach\">5</property><property name=\"bottom_attach\">6</prop"
  "erty><property name=\"x_options\">GTK_FILL</property><property name=\"y"
  "_options\">GTK_FILL</property></packing></child><child><object class=\""
  "GtkLabel\" id=\"label4\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"xalign\">0</p"
  "roperty><property name=\"label\" translatable=\"yes\">Refresh _rate:</p"
  "roperty><property name=\"use_underline\">True</property></object><packi"
  "ng><property name=\"top_attach\">4</property><property name=\"bottom_at"
  "tach\">5</property><property name=\"x_options\">GTK_FILL</property><pro"
  "perty name=\"y_options\">GTK_FILL</property></packing></child><child><o"
  "bject class=\"GtkLabel\" id=\"label3\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "xalign\">0</property><property name=\"label\" translatable=\"yes\">R_es"
  "olution:</property><property name=\"use_underline\">True</property></ob"
  "ject><packing><property name=\"top_attach\">3</property><property name="
  "\"bottom_attach\">4</property><property name=\"x_options\">GTK_FILL</pr"
  "operty><property name=\"y_options\">GTK_FILL</property></packing></chil"
  "d><child><object class=\"GtkLabel\" id=\"label-position\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"xalign\">0</property><property name=\"label\" trans"
  "latable=\"yes\">P_osition:</property><property name=\"use_underline\">T"
  "rue</property></object><packing><property name=\"top_attach\">2</proper"
  "ty><property name=\"bottom_attach\">3</property><property name=\"x_opti"
  "ons\">GTK_FILL</property><property name=\"y_options\">GTK_FILL</propert"
  "y></packing></child><child><object class=\"GtkCheckButton\" id=\"output"
  "-on\"><property name=\"label\" translatable=\"yes\">_Use this output</p"
  "roperty><property name=\"visible\">True</property><property name=\"can_"
  "focus\">True</property><property name=\"receives_default\">False</prope"
  "rty><property name=\"use_action_appearance\">False</property><property "
  "name=\"use_underline\">True</property><property name=\"draw_indicator\""
  ">True</property></object><packing><property name=\"right_attach\">2</pr"
  "operty><property name=\"x_options\">GTK_FILL</property><property name=\""
  "y_options\">GTK_FILL</property></packing></child><child><object class=\""
  "GtkCheckButton\" id=\"mirror-displays\"><property name=\"label\" transl"
  "atable=\"yes\">_Mirror displays</property><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">True</property><property name"
  "=\"receives_default\">False</property><property name=\"use_action_appea"
  "rance\">False</property><property name=\"use_underline\">True</property"
  "><property name=\"draw_indicator\">True</property></object><packing><pr"
  "operty name=\"right_attach\">2</property><property name=\"top_attach\">"
  "1</property><property name=\"bottom_attach\">2</property><property name"
  "=\"x_options\">GTK_FILL</property><property name=\"y_options\">GTK_FILL"
  "</property></packing></child><child><object class=\"GtkHBox\" id=\"hbox"
  "1\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><child><object class=\"GtkComboBox\" id=\"randr-pos"
  "ition\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property></object><packing><property name=\"expand\">Tru"
  "e</property><property name=\"fill\">True</property><property name=\"pos"
  "ition\">0</property></packing></child><child><object class=\"GtkComboBo"
  "x\" id=\"randr-active-displays\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property></object><packing><pro"
  "perty name=\"expand\">True</property><property name=\"fill\">True</prop"
  "erty><property name=\"position\">1</property></packing></child></object"
  "><packing><property name=\"left_attach\">1</property><property name=\"r"
  "ight_attach\">2</property><property name=\"top_attach\">2</property><pr"
  "operty name=\"bottom_attach\">3</property><property name=\"y_options\">"
  "GTK_FILL</property></packing></child></object><packing><property name=\""
  "expand\">True</property><property name=\"fill\">True</property><propert"
  "y name=\"position\">1</property></packing></child></object><packing><pr"
  "operty name=\"expand\">True</property><property name=\"fill\">True</pro"
  "perty><property name=\"position\">0</property></packing></child><child "
  "internal-child=\"action_area\"><object class=\"GtkHButtonBox\" id=\"dia"
  "log-action_area1\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"layout_style\">end<"
  "/property><child><object class=\"GtkButton\" id=\"button-help\"><proper"
  "ty name=\"label\">gtk-help</property><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">True</property><property name=\"re"
  "ceives_default\">True</property><property name=\"use_action_appearance\""
  ">False</property><property name=\"use_stock\">True</property></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">False</property><property name=\"position\">0</property><property na"
  "me=\"secondary\">True</property></packing></child><child><object class="
  "\"GtkButton\" id=\"button-close\"><property name=\"label\">gtk-close</p"
  "roperty><property name=\"visible\">True</property><property name=\"can_"
  "focus\">True</property><property name=\"receives_default\">True</proper"
  "ty><property name=\"use_action_appearance\">False</property><property n"
  "ame=\"use_stock\">True</property></object><packing><property name=\"exp"
  "and\">False</property><property name=\"fill\">False</property><property"
  " name=\"position\">1</property></packing></child></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">True</pro"
  "perty><property name=\"pack_type\">end</property><property name=\"posit"
  "ion\">0</property></packing></child><child><object class=\"GtkAlignment"
  "\" id=\"alignment1\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"bottom_padding\">"
  "6</property><property name=\"left_padding\">12</property><child><object"
  " class=\"GtkCheckButton\" id=\"minimal-autoshow\"><property name=\"labe"
  "l\" translatable=\"yes\">Configure _new displays when connected</proper"
  "ty><property name=\"visible\">True</property><property name=\"can_focus"
  "\">True</property><property name=\"receives_default\">False</property><"
  "property name=\"use_action_appearance\">False</property><property name="
  "\"use_underline\">True</property><property name=\"draw_indicator\">True"
  "</property></object></child></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">False</property><property name"
  "=\"position\">2</property></packing></child></object></child><action-wi"
  "dgets><action-widget response=\"-11\">button-help</action-widget><actio"
  "n-widget response=\"0\">button-close</action-widget></action-widgets></"
  "object></interface>"
};

static const unsigned display_dialog_ui_length = 10871u;

