/* automatically generated from mouse-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (mouse_dialog_ui)
#endif
#ifdef __GNUC__
static const char mouse_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char mouse_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"2.20\"/><object class=\"GtkAdjustment\" id=\"dclick-dist"
  "ance\"><property name=\"upper\">20</property><property name=\"value\">4"
  "</property><property name=\"step_increment\">1</property><property name"
  "=\"page_increment\">5</property></object><object class=\"GtkAdjustment\""
  " id=\"dclick-time\"><property name=\"lower\">100</property><property na"
  "me=\"upper\">2000</property><property name=\"value\">250</property><pro"
  "perty name=\"step_increment\">1</property><property name=\"page_increme"
  "nt\">100</property></object><object class=\"GtkAdjustment\" id=\"device"
  "-acceleration\"><property name=\"lower\">0.10000000000000001</property>"
  "<property name=\"upper\">10</property><property name=\"value\">2</prope"
  "rty><property name=\"step_increment\">0.10000000000000001</property><pr"
  "operty name=\"page_increment\">1</property></object><object class=\"Gtk"
  "Adjustment\" id=\"device-threshold\"><property name=\"lower\">1</proper"
  "ty><property name=\"upper\">30</property><property name=\"value\">4</pr"
  "operty><property name=\"step_increment\">1</property><property name=\"p"
  "age_increment\">5</property></object><object class=\"GtkAdjustment\" id"
  "=\"dnd-threshold\"><property name=\"lower\">1</property><property name="
  "\"upper\">50</property><property name=\"value\">8</property><property n"
  "ame=\"step_increment\">1</property><property name=\"page_increment\">10"
  "</property></object><object class=\"GtkImage\" id=\"image5\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"stock\">gtk-revert-to-saved</property></object><"
  "object class=\"GtkAdjustment\" id=\"synaptics-disable-duration\"><prope"
  "rty name=\"lower\">0.10000000000000001</property><property name=\"upper"
  "\">4</property><property name=\"value\">2</property><property name=\"st"
  "ep_increment\">0.10000000000000001</property><property name=\"page_incr"
  "ement\">1</property></object><object class=\"GtkListStore\" id=\"synapt"
  "ics-scroll-store\"><columns><column type=\"gchararray\"/><column type=\""
  "gboolean\"/></columns><data><row><col id=\"0\" translatable=\"yes\">Dis"
  "abled</col><col id=\"1\">True</col></row><row><col id=\"0\" translatabl"
  "e=\"yes\">Edge scrolling</col><col id=\"1\">True</col></row><row><col i"
  "d=\"0\" translatable=\"yes\">Two-finger scrolling</col><col id=\"1\">Tr"
  "ue</col></row><row><col id=\"0\" translatable=\"yes\">Circular scrollin"
  "g</col><col id=\"1\">True</col></row></data></object><object class=\"Gt"
  "kAdjustment\" id=\"theme-cursor-size\"><property name=\"lower\">16</pro"
  "perty><property name=\"upper\">48</property><property name=\"value\">24"
  "</property><property name=\"step_increment\">1</property><property name"
  "=\"page_increment\">11</property></object><object class=\"GtkListStore\""
  " id=\"wacom-rotation-store\"><columns><column type=\"gint\"/><column ty"
  "pe=\"gchararray\"/></columns><data><row><col id=\"0\">0</col><col id=\""
  "1\" translatable=\"yes\">None (right-handed)</col></row><row><col id=\""
  "0\">3</col><col id=\"1\" translatable=\"yes\">Half (left-handed)</col><"
  "/row><row><col id=\"0\">1</col><col id=\"1\" translatable=\"yes\">Clock"
  "wise</col></row><row><col id=\"0\">2</col><col id=\"1\" translatable=\""
  "yes\">Counterclockwise</col></row></data></object><object class=\"XfceT"
  "itledDialog\" id=\"mouse-dialog\"><property name=\"can_focus\">False</p"
  "roperty><property name=\"title\" translatable=\"yes\">Mouse and Touchpa"
  "d</property><property name=\"window_position\">center-on-parent</proper"
  "ty><property name=\"icon_name\">preferences-desktop-peripherals</proper"
  "ty><property name=\"type_hint\">dialog</property><property name=\"subti"
  "tle\" translatable=\"yes\">Configure pointer device behavior and appear"
  "ance</property><child internal-child=\"vbox\"><object class=\"GtkVBox\""
  " id=\"dialog-vbox1\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"spacing\">2</prop"
  "erty><child internal-child=\"action_area\"><object class=\"GtkHButtonBo"
  "x\" id=\"dialog-action_area1\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"layout_"
  "style\">end</property><child><object class=\"GtkButton\" id=\"button1\""
  "><property name=\"label\">gtk-close</property><property name=\"use_acti"
  "on_appearance\">False</property><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">True</property><property name=\"receive"
  "s_default\">True</property><property name=\"use_stock\">True</property>"
  "</object><packing><property name=\"expand\">False</property><property n"
  "ame=\"fill\">False</property><property name=\"position\">0</property></"
  "packing></child><child><object class=\"GtkButton\" id=\"button2\"><prop"
  "erty name=\"label\">gtk-help</property><property name=\"use_action_appe"
  "arance\">False</property><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">True</property><property name=\"receives_defau"
  "lt\">True</property><property name=\"use_stock\">True</property></objec"
  "t><packing><property name=\"expand\">False</property><property name=\"f"
  "ill\">False</property><property name=\"position\">0</property><property"
  " name=\"secondary\">True</property></packing></child></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">True<"
  "/property><property name=\"pack_type\">end</property><property name=\"p"
  "osition\">0</property></packing></child><child><object class=\"GtkNoteb"
  "ook\" id=\"plug-child\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">True</property><property name=\"border_width\">"
  "6</property><child><object class=\"GtkVBox\" id=\"vbox1\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"border_width\">12</property><property name=\"spacin"
  "g\">6</property><child><object class=\"GtkHBox\" id=\"hbox1\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"spacing\">12</property><child><object class=\"G"
  "tkLabel\" id=\"label7\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"label\" transl"
  "atable=\"yes\">De_vice:</property><property name=\"use_underline\">True"
  "</property><property name=\"mnemonic_widget\">device-combobox</property"
  "><property name=\"angle\">0.050000000000000003</property></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">0</property></packing></child"
  "><child><object class=\"GtkComboBox\" id=\"device-combobox\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty></object><packing><property name=\"expand\">True</property><prope"
  "rty name=\"fill\">True</property><property name=\"position\">1</propert"
  "y></packing></child></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">True</property><property name=\"positi"
  "on\">0</property></packing></child><child><object class=\"GtkCheckButto"
  "n\" id=\"device-enabled\"><property name=\"label\" translatable=\"yes\""
  ">_Enable this device</property><property name=\"use_action_appearance\""
  ">False</property><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">True</property><property name=\"receives_default\">Fal"
  "se</property><property name=\"use_underline\">True</property><property "
  "name=\"draw_indicator\">True</property></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">True</property><pro"
  "perty name=\"position\">1</property></packing></child><child><object cl"
  "ass=\"GtkNotebook\" id=\"device-notebook\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">True</property><child><objec"
  "t class=\"GtkVBox\" id=\"device-box\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "border_width\">6</property><property name=\"spacing\">6</property><chil"
  "d><object class=\"GtkFrame\" id=\"frame1\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"label_xalign\">0</property><property name=\"shadow_type\">none</pr"
  "operty><child><object class=\"GtkAlignment\" id=\"alignment1\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"left_padding\">12</property><child><object cla"
  "ss=\"GtkVBox\" id=\"vbox12\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"border_wi"
  "dth\">6</property><property name=\"spacing\">6</property><child><object"
  " class=\"GtkHBox\" id=\"hbox3\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"spacin"
  "g\">12</property><child><object class=\"GtkRadioButton\" id=\"device-ri"
  "ght-handed\"><property name=\"label\" translatable=\"yes\">Ri_ght-hande"
  "d</property><property name=\"use_action_appearance\">False</property><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Tr"
  "ue</property><property name=\"receives_default\">False</property><prope"
  "rty name=\"use_underline\">True</property><property name=\"active\">Tru"
  "e</property><property name=\"draw_indicator\">True</property></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">True</property><property name=\"position\">0</property></packing></c"
  "hild><child><object class=\"GtkRadioButton\" id=\"device-left-handed\">"
  "<property name=\"label\" translatable=\"yes\">Le_ft-handed</property><p"
  "roperty name=\"use_action_appearance\">False</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">False</property><property name=\"use_"
  "underline\">True</property><property name=\"draw_indicator\">True</prop"
  "erty><property name=\"group\">device-right-handed</property></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">1</property></packing></chi"
  "ld></object><packing><property name=\"expand\">True</property><property"
  " name=\"fill\">True</property><property name=\"position\">0</property><"
  "/packing></child><child><object class=\"GtkCheckButton\" id=\"device-re"
  "verse-scrolling\"><property name=\"label\" translatable=\"yes\">Reverse"
  " scroll d_irection</property><property name=\"use_action_appearance\">F"
  "alse</property><property name=\"visible\">True</property><property name"
  "=\"can_focus\">True</property><property name=\"receives_default\">False"
  "</property><property name=\"tooltip_text\" translatable=\"yes\">When se"
  "lected, the scroll wheel will work in the opposite direction</property>"
  "<property name=\"use_underline\">True</property><property name=\"draw_i"
  "ndicator\">True</property></object><packing><property name=\"expand\">T"
  "rue</property><property name=\"fill\">True</property><property name=\"p"
  "osition\">1</property></packing></child></object></child></object></chi"
  "ld><child type=\"label\"><object class=\"GtkLabel\" id=\"label14\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"label\" translatable=\"yes\">Buttons</prop"
  "erty><attributes><attribute name=\"weight\" value=\"bold\"/></attribute"
  "s></object></child></object><packing><property name=\"expand\">False</p"
  "roperty><property name=\"fill\">True</property><property name=\"positio"
  "n\">0</property></packing></child><child><object class=\"GtkFrame\" id="
  "\"frame2\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"label_xalign\">0</property>"
  "<property name=\"shadow_type\">none</property><child><object class=\"Gt"
  "kAlignment\" id=\"alignment2\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"left_pa"
  "dding\">12</property><child><object class=\"GtkTable\" id=\"table1\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"border_width\">6</property><property nam"
  "e=\"n_rows\">3</property><property name=\"n_columns\">2</property><prop"
  "erty name=\"column_spacing\">12</property><property name=\"row_spacing\""
  ">6</property><child><object class=\"GtkLabel\" id=\"device-acceleration"
  "-label\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"xalign\">0</property><propert"
  "y name=\"label\" translatable=\"yes\">Acceleratio_n:</property><propert"
  "y name=\"use_underline\">True</property><property name=\"mnemonic_widge"
  "t\">device-acceleration-scale</property></object><packing><property nam"
  "e=\"x_options\">GTK_FILL</property><property name=\"y_options\">GTK_FIL"
  "L</property></packing></child><child><object class=\"GtkHScale\" id=\"d"
  "evice-acceleration-scale\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">True</property><property name=\"tooltip_text"
  "\" translatable=\"yes\">The factor at which the pointer\'s speed will i"
  "ncrease as the mouse is moved</property><property name=\"update_policy\""
  ">delayed</property><property name=\"adjustment\">device-acceleration</p"
  "roperty><property name=\"round_digits\">1</property><property name=\"va"
  "lue_pos\">right</property></object><packing><property name=\"left_attac"
  "h\">1</property><property name=\"right_attach\">2</property></packing><"
  "/child><child><object class=\"GtkHScale\" id=\"device-threshold-scale\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"tooltip_text\" translatable=\"yes\">Th"
  "e number of pixels the pointer must move in a short time before it star"
  "ts accelerating</property><property name=\"update_policy\">delayed</pro"
  "perty><property name=\"adjustment\">device-threshold</property><propert"
  "y name=\"round_digits\">0</property><property name=\"digits\">0</proper"
  "ty><property name=\"value_pos\">right</property></object><packing><prop"
  "erty name=\"left_attach\">1</property><property name=\"right_attach\">2"
  "</property><property name=\"top_attach\">1</property><property name=\"b"
  "ottom_attach\">2</property></packing></child><child><object class=\"Gtk"
  "Label\" id=\"device-threshold-label\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "xalign\">0</property><property name=\"label\" translatable=\"yes\">Sens"
  "itivit_y:</property><property name=\"use_underline\">True</property><pr"
  "operty name=\"mnemonic_widget\">device-threshold-scale</property></obje"
  "ct><packing><property name=\"top_attach\">1</property><property name=\""
  "bottom_attach\">2</property><property name=\"x_options\">GTK_FILL</prop"
  "erty></packing></child><child><object class=\"GtkAlignment\" id=\"align"
  "ment7\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"xalign\">0</property><property"
  " name=\"xscale\">0</property><property name=\"yscale\">0</property><chi"
  "ld><object class=\"GtkButton\" id=\"device-reset-feedback\"><property n"
  "ame=\"label\" translatable=\"yes\">_Reset to Defaults</property><proper"
  "ty name=\"use_action_appearance\">False</property><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"receives_default\">True</property><property name=\"tooltip_t"
  "ext\" translatable=\"yes\">Set the acceleration and sensitivity for the"
  " selected device to the default values</property><property name=\"image"
  "\">image5</property><property name=\"use_underline\">True</property></o"
  "bject></child></object><packing><property name=\"right_attach\">2</prop"
  "erty><property name=\"top_attach\">2</property><property name=\"bottom_"
  "attach\">3</property></packing></child></object></child></object></chil"
  "d><child type=\"label\"><object class=\"GtkLabel\" id=\"label15\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"label\" translatable=\"yes\">Pointer Speed<"
  "/property><attributes><attribute name=\"weight\" value=\"bold\"/></attr"
  "ibutes></object></child></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">1</property></packing></child></object></child><child type=\"t"
  "ab\"><object class=\"GtkLabel\" id=\"label4\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label\" translatable=\"yes\">B_uttons and Feedback</property><pr"
  "operty name=\"use_underline\">True</property></object><packing><propert"
  "y name=\"tab_fill\">False</property></packing></child><child><object cl"
  "ass=\"GtkVBox\" id=\"synaptics-tab\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"b"
  "order_width\">6</property><property name=\"spacing\">6</property><child"
  "><object class=\"GtkFrame\" id=\"frame11\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"label_xalign\">0</property><property name=\"shadow_type\">none</pr"
  "operty><child><object class=\"GtkAlignment\" id=\"alignment13\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"left_padding\">12</property><child><object cl"
  "ass=\"GtkVBox\" id=\"vbox11\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"border_w"
  "idth\">6</property><property name=\"spacing\">6</property><child><objec"
  "t class=\"GtkCheckButton\" id=\"synaptics-disable-while-type\"><propert"
  "y name=\"label\" translatable=\"yes\">Disable touchpad _while typing</p"
  "roperty><property name=\"use_action_appearance\">False</property><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">True</"
  "property><property name=\"receives_default\">False</property><property "
  "name=\"tooltip_text\" translatable=\"yes\">When selected, the touchpad "
  "will be disabled when the keyboard is being used</property><property na"
  "me=\"use_underline\">True</property><property name=\"draw_indicator\">T"
  "rue</property></object><packing><property name=\"expand\">True</propert"
  "y><property name=\"fill\">True</property><property name=\"position\">0<"
  "/property></packing></child><child><object class=\"GtkAlignment\" id=\""
  "alignment8\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"left_padding\">18</propert"
  "y><child><object class=\"GtkHBox\" id=\"synaptics-disable-duration-box\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"spacing\">12</property><child><object"
  " class=\"GtkLabel\" id=\"label5\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"labe"
  "l\" translatable=\"yes\">Duratio_n:</property><property name=\"use_unde"
  "rline\">True</property><property name=\"mnemonic_widget\">synaptics-dis"
  "able-duration-scale</property></object><packing><property name=\"expand"
  "\">False</property><property name=\"fill\">True</property><property nam"
  "e=\"position\">0</property></packing></child><child><object class=\"Gtk"
  "HScale\" id=\"synaptics-disable-duration-scale\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">True</property><proper"
  "ty name=\"update_policy\">delayed</property><property name=\"adjustment"
  "\">synaptics-disable-duration</property><property name=\"round_digits\""
  ">1</property><property name=\"value_pos\">right</property></object><pac"
  "king><property name=\"expand\">True</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">1</property></packing></child"
  "></object></child></object><packing><property name=\"expand\">True</pro"
  "perty><property name=\"fill\">True</property><property name=\"position\""
  ">1</property></packing></child><child><object class=\"GtkCheckButton\" "
  "id=\"synaptics-tap-to-click\"><property name=\"label\" translatable=\"y"
  "es\">Tap touchpad to clic_k</property><property name=\"use_action_appea"
  "rance\">False</property><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">True</property><property name=\"receives_defaul"
  "t\">False</property><property name=\"use_underline\">True</property><pr"
  "operty name=\"draw_indicator\">True</property></object><packing><proper"
  "ty name=\"expand\">True</property><property name=\"fill\">True</propert"
  "y><property name=\"position\">2</property></packing></child></object></"
  "child></object></child><child type=\"label\"><object class=\"GtkLabel\""
  " id=\"label16\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"label\" translatable=\""
  "yes\">General</property><property name=\"use_markup\">True</property><a"
  "ttributes><attribute name=\"weight\" value=\"bold\"/></attributes></obj"
  "ect></child></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">True</property><property name=\"position\">0</"
  "property></packing></child><child><object class=\"GtkFrame\" id=\"frame"
  "10\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">False</property><property name=\"label_xalign\">0</property><prope"
  "rty name=\"shadow_type\">none</property><child><object class=\"GtkAlign"
  "ment\" id=\"alignment12\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"left_padding"
  "\">12</property><child><object class=\"GtkVBox\" id=\"vbox10\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"border_width\">6</property><property name=\"sp"
  "acing\">6</property><child><object class=\"GtkHBox\" id=\"hbox4\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"spacing\">12</property><child><object class"
  "=\"GtkLabel\" id=\"label23\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"xalign\">"
  "0</property><property name=\"label\" translatable=\"yes\">Scrolling _mo"
  "de:</property><property name=\"use_underline\">True</property><property"
  " name=\"mnemonic_widget\">synaptics-scroll</property></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">True<"
  "/property><property name=\"position\">0</property></packing></child><ch"
  "ild><object class=\"GtkComboBox\" id=\"synaptics-scroll\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"model\">synaptics-scroll-store</property><child><ob"
  "ject class=\"GtkCellRendererText\" id=\"cellrenderertext3\"/><attribute"
  "s><attribute name=\"sensitive\">1</attribute><attribute name=\"text\">0"
  "</attribute></attributes></child></object><packing><property name=\"exp"
  "and\">True</property><property name=\"fill\">True</property><property n"
  "ame=\"position\">1</property></packing></child></object><packing><prope"
  "rty name=\"expand\">True</property><property name=\"fill\">True</proper"
  "ty><property name=\"position\">0</property></packing></child><child><ob"
  "ject class=\"GtkCheckButton\" id=\"synaptics-scroll-horiz\"><property n"
  "ame=\"label\" translatable=\"yes\">Enable hori_zontal scrolling</proper"
  "ty><property name=\"use_action_appearance\">False</property><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">True</prope"
  "rty><property name=\"receives_default\">False</property><property name="
  "\"use_underline\">True</property><property name=\"draw_indicator\">True"
  "</property></object><packing><property name=\"expand\">True</property><"
  "property name=\"fill\">True</property><property name=\"position\">1</pr"
  "operty></packing></child></object></child></object></child><child type="
  "\"label\"><object class=\"GtkLabel\" id=\"label17\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"label\" translatable=\"yes\">Scrolling</property><propert"
  "y name=\"use_markup\">True</property><attributes><attribute name=\"weig"
  "ht\" value=\"bold\"/></attributes></object></child></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">True</p"
  "roperty><property name=\"position\">1</property></packing></child></obj"
  "ect><packing><property name=\"position\">1</property></packing></child>"
  "<child type=\"tab\"><object class=\"GtkLabel\" id=\"synaptics-label\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"label\" translatable=\"yes\">T_ouchpad<"
  "/property><property name=\"use_underline\">True</property></object><pac"
  "king><property name=\"position\">1</property><property name=\"tab_fill\""
  ">False</property></packing></child><child><object class=\"GtkVBox\" id="
  "\"wacom-tab\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"border_width\">6</proper"
  "ty><property name=\"spacing\">6</property><child><object class=\"GtkFra"
  "me\" id=\"frame12\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><property name=\"label_xalign\">0</"
  "property><property name=\"shadow_type\">none</property><child><object c"
  "lass=\"GtkAlignment\" id=\"alignment14\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><property name"
  "=\"left_padding\">12</property><child><object class=\"GtkTable\" id=\"t"
  "able2\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"border_width\">6</property><pr"
  "operty name=\"n_rows\">2</property><property name=\"n_columns\">2</prop"
  "erty><property name=\"column_spacing\">12</property><property name=\"ro"
  "w_spacing\">6</property><child><object class=\"GtkLabel\" id=\"label9\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"xalign\">0</property><property name=\""
  "label\" translatable=\"yes\">Trac_king mode:</property><property name=\""
  "use_underline\">True</property><property name=\"mnemonic_widget\">wacom"
  "-mode</property></object><packing><property name=\"x_options\">GTK_FILL"
  "</property></packing></child><child><object class=\"GtkLabel\" id=\"lab"
  "el10\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"xalign\">0</property><property "
  "name=\"label\" translatable=\"yes\">_Rotation:</property><property name"
  "=\"use_underline\">True</property><property name=\"mnemonic_widget\">wa"
  "com-rotation</property></object><packing><property name=\"top_attach\">"
  "1</property><property name=\"bottom_attach\">2</property><property name"
  "=\"x_options\">GTK_FILL</property></packing></child><child><object clas"
  "s=\"GtkComboBox\" id=\"wacom-mode\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"mo"
  "del\">wacom-mode-store</property><child><object class=\"GtkCellRenderer"
  "Text\" id=\"cellrenderertext1\"/><attributes><attribute name=\"text\">1"
  "</attribute></attributes></child></object><packing><property name=\"lef"
  "t_attach\">1</property><property name=\"right_attach\">2</property></pa"
  "cking></child><child><object class=\"GtkComboBox\" id=\"wacom-rotation\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"model\">wacom-rotation-store</propert"
  "y><child><object class=\"GtkCellRendererText\" id=\"cellrenderertext2\""
  "/><attributes><attribute name=\"text\">1</attribute></attributes></chil"
  "d></object><packing><property name=\"left_attach\">1</property><propert"
  "y name=\"right_attach\">2</property><property name=\"top_attach\">1</pr"
  "operty><property name=\"bottom_attach\">2</property></packing></child><"
  "/object></child></object></child><child type=\"label\"><object class=\""
  "GtkLabel\" id=\"label18\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"label\" tran"
  "slatable=\"yes\">General</property><property name=\"use_markup\">True</"
  "property><attributes><attribute name=\"weight\" value=\"bold\"/></attri"
  "butes></object></child></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">True</property><property name=\"pos"
  "ition\">0</property></packing></child></object><packing><property name="
  "\"position\">2</property></packing></child><child type=\"tab\"><object "
  "class=\"GtkLabel\" id=\"wacom-label\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "label\" translatable=\"yes\">Tab_let</property><property name=\"use_und"
  "erline\">True</property></object><packing><property name=\"position\">2"
  "</property><property name=\"tab_fill\">False</property></packing></chil"
  "d></object><packing><property name=\"expand\">True</property><property "
  "name=\"fill\">True</property><property name=\"position\">2</property></"
  "packing></child></object></child><child type=\"tab\"><object class=\"Gt"
  "kLabel\" id=\"label1\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"label\" transla"
  "table=\"yes\">_Devices</property><property name=\"use_underline\">True<"
  "/property></object><packing><property name=\"tab_fill\">False</property"
  "></packing></child><child><object class=\"GtkVBox\" id=\"vbox3\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"border_width\">12</property><property name=\""
  "spacing\">6</property><child><object class=\"GtkFrame\" id=\"frame3\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"label_xalign\">0</property><property na"
  "me=\"shadow_type\">none</property><child><object class=\"GtkAlignment\""
  " id=\"alignment3\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"left_padding\">12</"
  "property><child><object class=\"GtkVBox\" id=\"vbox4\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"border_width\">6</property><property name=\"spacing\">6"
  "</property><child><object class=\"GtkLabel\" id=\"mouse-dnd-label\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"xalign\">0</property><property name=\"lab"
  "el\" translatable=\"yes\">Th_reshold:</property><property name=\"use_un"
  "derline\">True</property><property name=\"mnemonic_widget\">dnd-thresho"
  "ld-scale</property></object><packing><property name=\"expand\">True</pr"
  "operty><property name=\"fill\">True</property><property name=\"position"
  "\">0</property></packing></child><child><object class=\"GtkHScale\" id="
  "\"dnd-threshold-scale\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">True</property><property name=\"tooltip_text\" "
  "translatable=\"yes\">The number of pixels the pointer must move before "
  "a drag operation will start</property><property name=\"update_policy\">"
  "delayed</property><property name=\"adjustment\">dnd-threshold</property"
  "><property name=\"digits\">0</property><property name=\"value_pos\">rig"
  "ht</property></object><packing><property name=\"expand\">True</property"
  "><property name=\"fill\">True</property><property name=\"position\">1</"
  "property></packing></child></object></child></object></child><child typ"
  "e=\"label\"><object class=\"GtkLabel\" id=\"label6\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"label\" translatable=\"yes\">Drag and Drop</property><at"
  "tributes><attribute name=\"weight\" value=\"bold\"/></attributes></obje"
  "ct></child></object><packing><property name=\"expand\">False</property>"
  "<property name=\"fill\">True</property><property name=\"position\">0</p"
  "roperty></packing></child><child><object class=\"GtkFrame\" id=\"frame4"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"label_xalign\">0</property><propert"
  "y name=\"shadow_type\">none</property><child><object class=\"GtkAlignme"
  "nt\" id=\"alignment4\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"left_padding\">"
  "12</property><child><object class=\"GtkVBox\" id=\"vbox5\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"border_width\">6</property><property name=\"spacin"
  "g\">6</property><child><object class=\"GtkLabel\" id=\"dclick-time-labe"
  "l\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"xalign\">0</property><property nam"
  "e=\"label\" translatable=\"yes\">Ti_me:</property><property name=\"use_"
  "underline\">True</property><property name=\"mnemonic_widget\">dclick-ti"
  "me-scale</property></object><packing><property name=\"expand\">True</pr"
  "operty><property name=\"fill\">True</property><property name=\"position"
  "\">0</property></packing></child><child><object class=\"GtkHScale\" id="
  "\"dclick-time-scale\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">True</property><property name=\"tooltip_text\" tr"
  "anslatable=\"yes\">Two mouse clicks in less than this length of time (i"
  "n milliseconds) will be considered a double click</property><property n"
  "ame=\"update_policy\">delayed</property><property name=\"adjustment\">d"
  "click-time</property><property name=\"digits\">0</property><property na"
  "me=\"value_pos\">right</property></object><packing><property name=\"exp"
  "and\">True</property><property name=\"fill\">True</property><property n"
  "ame=\"position\">1</property></packing></child><child><object class=\"G"
  "tkLabel\" id=\"dclick-distance-label\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "xalign\">0</property><property name=\"label\" translatable=\"yes\">D_is"
  "tance:</property><property name=\"use_underline\">True</property><prope"
  "rty name=\"mnemonic_widget\">dclick-distance-scale</property></object><"
  "packing><property name=\"expand\">True</property><property name=\"fill\""
  ">True</property><property name=\"position\">2</property></packing></chi"
  "ld><child><object class=\"GtkHScale\" id=\"dclick-distance-scale\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">True"
  "</property><property name=\"tooltip_text\" translatable=\"yes\">The mou"
  "se pointer cannot move farther than this distance between two clicks fo"
  "r them to be considered a double click</property><property name=\"updat"
  "e_policy\">delayed</property><property name=\"adjustment\">dclick-dista"
  "nce</property><property name=\"digits\">0</property><property name=\"va"
  "lue_pos\">right</property></object><packing><property name=\"expand\">T"
  "rue</property><property name=\"fill\">True</property><property name=\"p"
  "osition\">3</property></packing></child></object></child></object></chi"
  "ld><child type=\"label\"><object class=\"GtkLabel\" id=\"label8\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"label\" translatable=\"yes\">Double Click</"
  "property><attributes><attribute name=\"weight\" value=\"bold\"/></attri"
  "butes></object></child></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">True</property><property name=\"pos"
  "ition\">1</property></packing></child></object><packing><property name="
  "\"position\">1</property></packing></child><child type=\"tab\"><object "
  "class=\"GtkLabel\" id=\"label2\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"label"
  "\" translatable=\"yes\">_Behavior</property><property name=\"use_underl"
  "ine\">True</property></object><packing><property name=\"position\">1</p"
  "roperty><property name=\"tab_fill\">False</property></packing></child><"
  "child><object class=\"GtkHBox\" id=\"themes-hbox\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"border_width\">12</property><property name=\"spacing\">12<"
  "/property><child><object class=\"GtkScrolledWindow\" id=\"scrolledwindo"
  "w2\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">True</property><property name=\"hscrollbar_policy\">automatic</pro"
  "perty><property name=\"vscrollbar_policy\">automatic</property><propert"
  "y name=\"shadow_type\">etched-in</property><child><object class=\"GtkTr"
  "eeView\" id=\"theme-treeview\"><property name=\"width_request\">200</pr"
  "operty><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">True</property><property name=\"headers_visible\">False</propert"
  "y></object></child></object><packing><property name=\"expand\">True</pr"
  "operty><property name=\"fill\">True</property><property name=\"position"
  "\">0</property></packing></child><child><object class=\"GtkVBox\" id=\""
  "vbox9\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"spacing\">6</property><child><"
  "object class=\"GtkFrame\" id=\"frame5\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"label_xalign\">0</property><property name=\"shadow_type\">none</prope"
  "rty><child><object class=\"GtkAlignment\" id=\"alignment5\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"left_padding\">12</property><child><object class="
  "\"GtkHBox\" id=\"hbox7\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"border_width\""
  ">6</property><property name=\"spacing\">12</property><child><object cla"
  "ss=\"GtkLabel\" id=\"label21\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"label\""
  " translatable=\"yes\">Cursor si_ze:</property><property name=\"use_unde"
  "rline\">True</property><property name=\"mnemonic_widget\">spin1</proper"
  "ty></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">0</property>"
  "</packing></child><child><object class=\"GtkSpinButton\" id=\"spin1\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">T"
  "rue</property><property name=\"primary_icon_activatable\">False</proper"
  "ty><property name=\"secondary_icon_activatable\">False</property><prope"
  "rty name=\"primary_icon_sensitive\">True</property><property name=\"sec"
  "ondary_icon_sensitive\">True</property><property name=\"adjustment\">th"
  "eme-cursor-size</property><property name=\"snap_to_ticks\">True</proper"
  "ty><property name=\"numeric\">True</property></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">True</propert"
  "y><property name=\"position\">1</property></packing></child></object></"
  "child></object></child><child type=\"label\"><object class=\"GtkLabel\""
  " id=\"label20\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"label\" translatable=\""
  "yes\">Size</property><attributes><attribute name=\"weight\" value=\"bol"
  "d\"/></attributes></object></child></object><packing><property name=\"e"
  "xpand\">False</property><property name=\"fill\">True</property><propert"
  "y name=\"position\">0</property></packing></child><child><object class="
  "\"GtkFrame\" id=\"frame6\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"label_xalig"
  "n\">0</property><property name=\"shadow_type\">none</property><child><o"
  "bject class=\"GtkAlignment\" id=\"alignment6\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"border_width\">6</property><property name=\"xalign\">0</proper"
  "ty><property name=\"yalign\">0</property><property name=\"xscale\">0</p"
  "roperty><property name=\"yscale\">0</property><property name=\"top_padd"
  "ing\">6</property><property name=\"bottom_padding\">6</property><proper"
  "ty name=\"left_padding\">18</property><property name=\"right_padding\">"
  "6</property><child><object class=\"GtkImage\" id=\"theme-preview\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"stock\">gtk-missing-image</property></obje"
  "ct></child></object></child><child type=\"label\"><object class=\"GtkLa"
  "bel\" id=\"label22\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"label\" translata"
  "ble=\"yes\">Preview</property><attributes><attribute name=\"weight\" va"
  "lue=\"bold\"/></attributes></object></child></object><packing><property"
  " name=\"expand\">False</property><property name=\"fill\">True</property"
  "><property name=\"position\">1</property></packing></child></object><pa"
  "cking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">1</property></packing></chi"
  "ld></object><packing><property name=\"position\">2</property></packing>"
  "</child><child type=\"tab\"><object class=\"GtkLabel\" id=\"label3\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"label\" translatable=\"yes\">_Theme</pro"
  "perty><property name=\"use_underline\">True</property></object><packing"
  "><property name=\"position\">2</property><property name=\"tab_fill\">Fa"
  "lse</property></packing></child></object><packing><property name=\"expa"
  "nd\">True</property><property name=\"fill\">True</property><property na"
  "me=\"position\">1</property></packing></child></object></child><action-"
  "widgets><action-widget response=\"0\">button1</action-widget><action-wi"
  "dget response=\"-11\">button2</action-widget></action-widgets></object>"
  "<object class=\"GtkListStore\" id=\"wacom-mode-store\"><columns><column"
  " type=\"gchararray\"/><column type=\"gchararray\"/></columns><data><row"
  "><col id=\"0\">ABSOLUTE</col><col id=\"1\" translatable=\"yes\">Pen (ab"
  "solute)</col></row><row><col id=\"0\">RELATIVE</col><col id=\"1\" trans"
  "latable=\"yes\">Mouse (relative)</col></row></data></object></interface"
  ">"
};

static const unsigned mouse_dialog_ui_length = 39386u;

